### ISSUE TITLE
Support for browser pages

### ISSUE THREAD

**Issue by platy** [webextension-toolbox/webpack-webextension-plugin#15]
The current dev reload script is added to the manifest under `backend.scripts`, which creates a conflict if the app is using a backend page instead `backend.page` as only one of these methods may be used at a time. 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background

I suppose that background pages could be made to work by inserting a `<script>` element on the background page, but it might be a bit messy.

**Comment by balcsida** [comment]
Hi @platy,

Thank you for bringing up this matter.
If I remember correctly, Chrome deprecated the `background.page` key, but I can't find that info right now. Strange...

I will look into this matter more deeper. I also pinged @HaNdTriX on this matter.

Kind regards,
@balcsida

**Comment by witi83** [comment]
@balcsida @HaNdTriX , any news on this? I've also encountered this issue.

**Comment by balcsida** [comment]
Hi @witi83,

No, unfortunately I didn't have time and energy to look into this.

Kind regards

**Comment by platy** [comment]
I switched to using `background.scripts` so I don't have this problem any more. I was using `background.page` in order to load my script as a module but I started using webpack and the modules were no longer necessary.

**Comment by tm1000** [comment]
Looking through the code this was done quite a while ago (though now it's deprecated)
