### ISSUE TITLE
Manifest V3 background.serviceworker

### ISSUE THREAD

**Issue by jchnxu** [webextension-toolbox/webpack-webextension-plugin#163]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/4531670/161773036-6d471841-f152-4b53-8462-df02b6c8321e.png">

I believe this is not the case for manifest V3?

**Comment by tm1000** [comment]
This is already being worked on

**Comment by tm1000** [comment]
You can also use the scoped package which is the fixed version: `npm i @webextension-toolbox/webextension-toolbox`

**Comment by jchnxu** [comment]
I tried 0.4.1 (latest) but it does not work. Guess I'll need to use [#skipmanifestvalidation](https://github.com/webextension-toolbox/webpack-webextension-plugin#skipmanifestvalidation)

But however the scripts generates a background.scripts field which prevents testing. I'll have to modify the source code anyway.

**Comment by tm1000** [comment]
@jchnxu 0.4.1 is not the latest

https://www.npmjs.com/package/webpack-webextension-plugin is at 1.0.0 (Not scoped, old but newer than what you have)

https://www.npmjs.com/package/@webextension-toolbox/webpack-webextension-plugin is at 2.0.3 and is the scoped version (latest)
