### ISSUE TITLE
Localized strings are now being removed from manifest.json

### ISSUE THREAD

**Issue by rthaut** [webextension-toolbox/webpack-webextension-plugin#167]
It seems [localized strings in the manifest.json file](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#internationalizing_manifest.json) are erroneously being removed during the "compilation" process.

A source `manifest.json` file containing the following contents:

```json
{
  "manifest_version": 3,
  "name": "__MSG_extensionName__",
  "description": "__MSG_extensionDescription__",
  "version": "1.0"
}
```

Results in this **invalid** `manifest.json` (note the empty `name` and `description` properties):
```json
{
  "manifest_version": 3,
  "name": "",
  "description": "",
  "version": "1.0"
}
```

However, the expected output is:
```json
{
  "manifest_version": 3,
  "name": "__MSG_extensionName__",
  "description": "__MSG_extensionDescription__",
  "version": "1.0"
}
```

I haven't done any debugging yet, but a cursory glance leads me to believe the [`transformManifestValuesFromENV()` method](https://github.com/webextension-toolbox/webpack-webextension-plugin/blob/2.0.1/src/plugin/index.ts#L456-L499) introduced in v2.0.1 is the culprit, as the was not an issue in v1.0,0 and earlier.

**Comment by tm1000** [comment]
Thanks!
