### ISSUE TITLE
Manifest.json custom path

### ISSUE THREAD

**Issue by t-geindre** [webextension-toolbox/webpack-webextension-plugin#48]
Hi! Thank for the great job that has been done here.

I have a question though, is there a way to define a custom path to the `manifest.json` file?

Since I'm not very use to work with webpack and related tools, I might be missing something. But, as far as I understand, the plugin will always look for the manifest in `options.context` path. Maybe an additional option to set the manifest path could do the job? With a fallback to the default one.

**Comment by t-geindre** [comment]
I'd be happy to open a PR if adding an options seems OK to you.

**Comment by tm1000** [comment]
Can you let me know the thinking here on this?
