### ISSUE TITLE
Docs on usage not working

### ISSUE THREAD

**Issue by vwheezy** [webextension-toolbox/webpack-webextension-plugin#625]
The docs on [Usage](https://github.com/webextension-toolbox/webpack-webextension-plugin#Usage) did not work in my setup. I was getting a TypeError: saying `WebextensionPlugin` is not a constructor. I had to replace it with the following:
 
```javascript
import { WebextensionPlugin } from "@webextension-toolbox/webpack-webextension-plugin";

const config = {
  plugins: [
    new WebextensionPlugin({
      vendor: "chrome",
    }),
  ],
};
``` 

I can submit a PR for this, but I'm not sure if this is the correct behavior or if my setup had to do with the issue.

**Comment by tm1000** [comment]
I just changed to ESM so this is probably 100% correct. You can submit the PR or I will do it at a later date. Thanks for the info!

**Comment by vwheezy** [comment]
Just pushed PR #626
